const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const sources = [
  path.join(__dirname, 'blind-test-20260909/roi-update-review/local-results.json'),
  path.join(__dirname, 'blind-test-20260909/batch-009-014/local-results.json'),
];
const truth = {
  '001.png':'simultaneous','002.png':'simultaneous','003.png':'simultaneous',
  '004.png':'simultaneous','005.png':'simultaneous','006.png':'H2O_only',
  '007.png':'H2O_only','008.png':'H2_only','009.jpg':'H2O_only',
  '010.jpg':'H2_only','011.jpg':'H2_only','012.jpg':'simultaneous',
  '013jpg.jpg':'simultaneous','014.jpg':'simultaneous',
};
const concentrations = {
  '001.png':[4,60],'002.png':[4,60],
  '003.png':[4,40],'004.png':[4,40],'005.png':[4,40],
  '006.png':[0,60],'007.png':[0,60],'008.png':[2,20],
  '009.jpg':[0,80],'010.jpg':[4,20],'011.jpg':[4,20],
  '012.jpg':[4,60],'013jpg.jpg':[4,70],'014.jpg':[4,50],
};
const groups = {
  '001.png':'scene-001-002','002.png':'scene-001-002',
  '003.png':'scene-003-005','004.png':'scene-003-005','005.png':'scene-003-005',
  '006.png':'scene-006-007','007.png':'scene-006-007',
  '008.png':'scene-008','009.jpg':'scene-009',
  '010.jpg':'scene-010-011','011.jpg':'scene-010-011',
  '012.jpg':'scene-012','013jpg.jpg':'scene-013','014.jpg':'scene-014',
};
const features = ['flame_a','flame_b','drop_a','drop_b','top_a','top_b','flame_drop_a','flame_drop_b'];

function delta(raw, baseline, name) {
  if (name === 'flame_drop_a') return delta(raw, baseline, 'flame_a') - delta(raw, baseline, 'drop_a');
  if (name === 'flame_drop_b') return delta(raw, baseline, 'flame_b') - delta(raw, baseline, 'drop_b');
  const m = /^(flame|drop|drop_registered|top)_([Lab])$/.exec(name);
  if (m) {
    const bg = 'bg_' + m[2];
    return (raw[name] - raw[bg]) - (baseline[name] - baseline[bg]);
  }
  return raw[name] - baseline[name];
}

const anchors = [];
for (const source of sources) {
  const data = JSON.parse(fs.readFileSync(source, 'utf8'));
  for (const item of data.results) {
    if (!truth[item.file]) throw new Error('Missing truth label for ' + item.file);
    anchors.push({file:item.file, group:groups[item.file], state:truth[item.file],
      h2_percent:concentrations[item.file][0],rh_percent:concentrations[item.file][1],
      values:features.map(name => delta(item.raw._raw, data.calibration.BL, name))});
  }
}
const means = features.map((_, j) => anchors.reduce((s, a) => s + a.values[j], 0) / anchors.length);
const scales = features.map((_, j) => {
  const variance = anchors.reduce((s, a) => s + (a.values[j] - means[j]) ** 2, 0) / Math.max(1, anchors.length - 1);
  return Math.max(Math.sqrt(variance), 0.5);
});
const model = {type:'standardized_photo_anchor_1nn',version:'2026.09.10-v1',features,means,scales,anchors,
  acceptance_rms:0.85,note:'Labeled smartphone still anchors 001-014; independent capture validation required'};
fs.writeFileSync(path.join(root, 'sensor-photo-state-model.js'),
  '// Generated by training/build_photo_state_anchors.cjs\nwindow.SENSOR_PHOTO_STATE_MODEL=' + JSON.stringify(model) + ';\n');
const output = path.join(__dirname, 'output/v45-pattern-roi/photo_state_anchors.json');
fs.mkdirSync(path.dirname(output), {recursive:true});
fs.writeFileSync(output, JSON.stringify(model, null, 2));
console.log(JSON.stringify({anchors:anchors.length,features,output:'sensor-photo-state-model.js'},null,2));
