"""Audit an automatic optical 2-vs-3 specialist against the four-band model.

Pseudo labels are generated by ``h2_optical_pseudolabel_analysis``.  The fixed
test_2 anchor is allowed in specialist training, but specialist overrides are
never scored on test_2 because it defined the optical reference.  For every
other evaluation video, model family and asymmetric thresholds are selected
using only the remaining videos.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from h2_optical_pseudolabel_analysis import optical_labels


LABELS = (0, 2, 3, 4)
DISPLAY = ("0-1", "2", "3", "4")
THRESHOLDS = (.50, .55, .60, .65, .70, .75, .80, .85, .90, .95, .99, 1.01)


def estimator(kind: str):
    if kind == "lda":
        return make_pipeline(StandardScaler(), LinearDiscriminantAnalysis(
            solver="lsqr", shrinkage="auto"))
    return make_pipeline(StandardScaler(), LogisticRegression(
        C=.2, max_iter=4000, class_weight="balanced", random_state=42))


def report(truth, prediction, groups):
    matrix = confusion_matrix(truth, prediction, labels=LABELS)
    recall = np.divide(np.diag(matrix), matrix.sum(axis=1),
                       out=np.zeros(4, dtype=float), where=matrix.sum(axis=1) > 0)
    per_run = {run: float(np.mean(prediction[groups == run] == truth[groups == run]))
               for run in sorted(set(groups))}
    return {
        "exact": float(np.mean(prediction == truth)),
        "video_macro_exact": float(np.mean(list(per_run.values()))),
        "mae_percent_points": float(np.mean(np.abs(prediction - truth))),
        "recall": {DISPLAY[i]: float(recall[i]) for i in range(4)},
        "confusion": matrix.tolist(),
        "per_run_exact": per_run,
    }


def safe(candidate, baseline, require_two_gain=True):
    eps = 1e-12
    protected = ("0-1", "3", "4")
    return (
        candidate["exact"] + eps >= baseline["exact"]
        and candidate["video_macro_exact"] + eps >= baseline["video_macro_exact"]
        and candidate["mae_percent_points"] <= baseline["mae_percent_points"] + eps
        and all(candidate["recall"][label] + eps >= baseline["recall"][label]
                for label in protected)
        and (not require_two_gain
             or candidate["recall"]["2"] > baseline["recall"]["2"] + eps)
    )


def safe_per_video(truth, candidate, baseline, groups):
    """Reject a rule that hides an aggregate gain by damaging one meta video."""
    eps = 1e-12
    for run in sorted(set(groups)):
        use = groups == run
        old = report(truth[use], baseline[use], groups[use])
        new = report(truth[use], candidate[use], groups[use])
        if new["exact"] + eps < old["exact"]:
            return False
        # Protect 3% only when this video contains a 3% reference row.
        if np.any(truth[use] == 3) and new["recall"]["3"] + eps < old["recall"]["3"]:
            return False
    return True


def gate(baseline, p2, p3, threshold_23, threshold_32):
    result = baseline.copy()
    result[(baseline == 2) & (p3 >= threshold_23)] = 3
    result[(baseline == 3) & (p2 >= threshold_32)] = 2
    return result


def crossfit_baseline(x, y, groups):
    prediction = np.full(len(y), -1)
    for held_out in sorted(set(groups)):
        train, test = groups != held_out, groups == held_out
        model = estimator("lda")
        model.fit(x[train], y[train])
        prediction[test] = model.predict(x[test])
    return prediction


def specialist_probabilities(base_x, base_groups, pseudo_x, pseudo_y,
                             pseudo_groups, pseudo_selected, kind):
    p2 = np.zeros(len(base_x), dtype=float)
    p3 = np.zeros(len(base_x), dtype=float)
    for held_out in sorted(set(base_groups)):
        # test_2 is the fixed metrology anchor for other videos.  It is excluded
        # only when predicting test_2 itself; those predictions are never gated.
        train = pseudo_selected & (pseudo_groups != held_out)
        model = estimator(kind)
        model.fit(pseudo_x[train], pseudo_y[train])
        test = base_groups == held_out
        probabilities = model.predict_proba(base_x[test])
        classes = list(model.classes_)
        p2[test] = probabilities[:, classes.index(2)]
        p3[test] = probabilities[:, classes.index(3)]
    return p2, p3


def rank(candidate, baseline, threshold_23, threshold_32):
    return (
        candidate["recall"]["2"] - baseline["recall"]["2"],
        candidate["video_macro_exact"], candidate["exact"],
        -candidate["mae_percent_points"],
        -(threshold_23 + threshold_32),
    )


def plot(path, baseline, candidate):
    fig, axes = plt.subplots(1, 2, figsize=(10.5, 4.5), constrained_layout=True)
    maximum = max(np.asarray(baseline["confusion"]).max(),
                  np.asarray(candidate["confusion"]).max())
    for axis, title, metrics in ((axes[0], "Four-band baseline", baseline),
                                 (axes[1], "Nested optical specialist", candidate)):
        matrix = np.asarray(metrics["confusion"])
        image = axis.imshow(matrix, cmap="Blues", vmin=0, vmax=maximum)
        for row in range(4):
            for column in range(4):
                axis.text(column, row, str(matrix[row, column]), ha="center", va="center")
        axis.set(xticks=range(4), xticklabels=DISPLAY, yticks=range(4),
                 yticklabels=DISPLAY, xlabel="Predicted H2 band",
                 ylabel="Reference H2 band", title=title)
        axis.text(.5, -.22,
                  f"exact={metrics['exact']:.3f}  macro={metrics['video_macro_exact']:.3f}\n"
                  f"R2={metrics['recall']['2']:.3f}  R3={metrics['recall']['3']:.3f}",
                  transform=axis.transAxes, ha="center", fontsize=9)
    fig.colorbar(image, ax=axes, shrink=.8, label="Frames")
    fig.savefig(path, dpi=190)
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--four-band-cache", type=Path, required=True)
    parser.add_argument("--pseudo-cache", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)

    base = np.load(args.four_band_cache, allow_pickle=False)
    bx, by, bg = base["x"], base["y"], base["groups"]
    pseudo = np.load(args.pseudo_cache, allow_pickle=False)
    px, pg, pt = pseudo["x"], pseudo["groups"], pseudo["times"]
    py, selected, *_ = optical_labels(px, pg, pt)

    baseline_all = crossfit_baseline(bx, by, bg)
    # Avoid circular scoring on the run that defines the optical anchors.
    evaluated = bg != "test_2"
    x, y, groups = bx[evaluated], by[evaluated], bg[evaluated]
    baseline = baseline_all[evaluated]
    baseline_metrics = report(y, baseline, groups)

    probabilities = {}
    for kind in ("lda", "logistic"):
        p2, p3 = specialist_probabilities(bx, bg, px, py, pg, selected, kind)
        probabilities[kind] = (p2[evaluated], p3[evaluated])
    probabilities["mean_consensus"] = (
        np.mean([value[0] for value in probabilities.values()], axis=0),
        np.mean([value[1] for value in probabilities.values()], axis=0),
    )
    probabilities["strict_consensus"] = (
        np.min([value[0] for key, value in probabilities.items()
                if key in ("lda", "logistic")], axis=0),
        np.min([value[1] for key, value in probabilities.items()
                if key in ("lda", "logistic")], axis=0),
    )

    final = baseline.copy()
    choices = {}
    for held_out in sorted(set(groups)):
        meta = groups != held_out
        meta_baseline = report(y[meta], baseline[meta], groups[meta])
        feasible = []
        for kind, (p2, p3) in probabilities.items():
            for threshold_23 in THRESHOLDS:
                for threshold_32 in THRESHOLDS:
                    prediction = gate(baseline[meta], p2[meta], p3[meta],
                                      threshold_23, threshold_32)
                    metrics = report(y[meta], prediction, groups[meta])
                    if (safe(metrics, meta_baseline)
                            and safe_per_video(y[meta], prediction,
                                               baseline[meta], groups[meta])):
                        feasible.append((rank(metrics, meta_baseline,
                                              threshold_23, threshold_32),
                                         kind, threshold_23, threshold_32, metrics))
        use = groups == held_out
        if feasible:
            _, kind, threshold_23, threshold_32, meta_metrics = max(feasible)
            p2, p3 = probabilities[kind]
            final[use] = gate(baseline[use], p2[use], p3[use],
                              threshold_23, threshold_32)
            choices[held_out] = {
                "feasible": True, "model": kind,
                "threshold_2_to_3": threshold_23,
                "threshold_3_to_2": threshold_32,
                "meta_metrics": meta_metrics,
            }
        else:
            choices[held_out] = {"feasible": False, "action": "keep baseline"}

    final_metrics = report(y, final, groups)
    changed = final != baseline

    # This grid uses all evaluation labels and is diagnostic only.  It answers
    # whether the specialist has any attainable safe operating point; it cannot
    # be used as an unbiased deployment threshold.
    diagnostic = []
    for kind, (p2, p3) in probabilities.items():
        for threshold_23 in THRESHOLDS:
            for threshold_32 in THRESHOLDS:
                prediction = gate(baseline, p2, p3, threshold_23, threshold_32)
                metrics = report(y, prediction, groups)
                if (safe(metrics, baseline_metrics)
                        and safe_per_video(y, prediction, baseline, groups)):
                    diagnostic.append((rank(metrics, baseline_metrics,
                                            threshold_23, threshold_32), {
                        "model": kind, "threshold_2_to_3": threshold_23,
                        "threshold_3_to_2": threshold_32,
                        "metrics": metrics,
                    }))
    diagnostic_best = max(diagnostic, key=lambda item: item[0])[1] if diagnostic else None
    payload = {
        "protocol": "nested leave-one-video-out automatic optical 2/3 specialist",
        "data": {
            "pseudo_selected": int(selected.sum()),
            "pseudo_2": int((selected & (py == 2)).sum()),
            "pseudo_3": int((selected & (py == 3)).sum()),
            "evaluation_rows": int(len(y)),
            "evaluation_videos": sorted(set(groups)),
            "excluded_from_scoring": "test_2 (defines optical anchors)",
            "rh30": "screened separately and excluded; no optical-3 candidates",
        },
        "constraints": {
            "required_gain": "2% recall strictly higher on every meta-training selection",
            "protected": "0-1, 3 and 4 recall; exact; video-macro exact; MAE",
        },
        "baseline": baseline_metrics,
        "nested_specialist": final_metrics,
        "aggregate_constraints_passed": bool(
            safe(final_metrics, baseline_metrics)
            and safe_per_video(y, final, baseline, groups)),
        "changed_frames": int(changed.sum()),
        "changes": {
            "2_to_3": int(np.sum((baseline == 2) & (final == 3))),
            "3_to_2": int(np.sum((baseline == 3) & (final == 2))),
        },
        "selected_by_held_out_video": choices,
        "diagnostic_global_safe_operating_point": diagnostic_best,
        "diagnostic_warning": "selected on all evaluation labels; feasibility check only",
        "deployment_ready": bool(
            safe(final_metrics, baseline_metrics)
            and safe_per_video(y, final, baseline, groups)),
    }
    (args.output / "metrics.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    plot(args.output / "optical_specialist_confusion.png", baseline_metrics, final_metrics)
    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
